build:
  environment:
    php:
      version: 7.4.7
  tests:
    override:
      - command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
        coverage:
          file: 'coverage.xml'
          format: 'php-clover'

checks:
  php: true

filter:
  excluded_paths:
    - ".github/"
    - "examples/"
    - "tests/"
